### ISSUE TITLE
USER STORY: Deployment

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-backend#15]
* [ ] - #14 

As a **developer** I can **deploy my application** so that **the frontend application can save data via an API**.

## Acceptance criteria
* Deployed to Heroku
* Private variables are not shared in GitHub repository

## Tasks
- [x] Setup Django project, DRF & apps
- [x] Link PostgreSQL via Elephant SQL
- [x] Link White Noise (for admin static files)
- [x] Create Config Vars in Heroku 
- [x] Hide SECRET_KEY in env.py
- [x] Add domain to CLIENT_ORIGIN
- [x] Install gunicorn
- [x] Install & set up django-cors-headers 
- [x] Create Procfile
