### ISSUE TITLE
USER STORY: Sign Up & Log In

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-backend#4]
* [ ] - #9  

As a **user** I can **Sign Up & Log In** so that **I can use the application**.

## Acceptance criteria
* Users can sign up via a form
* Users can log in via a form
* Form inputs are validated
* Form errors are communicated to the user
* The log in status is made clear to the user via on screen messages and UI state

## Tasks
- [x] Install & set up 'django-allauth' and 'dj-rest-auth'
- [x] Create Sign Up form
- [x] Create Log In form
- [x] Display any errors.message in the UI
- [x] Update the account icon text on sign in from "log in" to "user"
- [x] Display a notification to the user on log in
