### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-backend#5]
* [ ] - #9 

As a **user** I can **log out of my account** so that **my data doesn't appear when other use the device**.

## Acceptance criteria
* A log out button.
* Log out status is clearly communicated to the user.
* The users save state (notes, folder & prompts) is not shown in the UI after logging out.

## Tasks
- [x] Create log out button
- [x] Show log out message in UserMessages context
- [x] Reset state: notes, folders, prompts
