### ISSUE TITLE
USER STORY: Create, read, update and delete a note

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-backend#6]
* [ ] - #10 

As a **user** I can **create a note** so that **I can read it at a later date or on a different device**.

## Acceptance criteria
* User can create a note
* User can view a list of their notes
* User can edit a note
* User can delete a note
* Only a user can access or modify their own notes

## Tasks
- [x] Create a Note model
- [x] Create Note views.py
- [x] Create a Note serializer
- [x] Set up permissions and queryset
