### ISSUE TITLE
USER STORY: Create, read, update and delete a folder

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-backend#7]
* [ ] - #11 

As a **user** I can **save, edit and delete my folders** so that **I can retrieve and manage my folders**.

## Acceptance criteria
* User can create a folder
* User can view a list of their folder
* User can edit a folder
* User can delete a folder
* Only a user can access or modify their own folder

## Tasks
- [x] Create a Folder model
- [x] Create Folder views.py
- [x] Create a Folder serializer
- [x] Set up permissions and queryset
