### ISSUE TITLE
USER STORY: Create, read and delete a custom prompt

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/transcriber-backend#8]
* [ ] - #12 

As a **user** I can **save and delete custom prompt** so that **I can use custom AI formatting**.

## Acceptance criteria
* User can create a custom prompt
* User can view a list of their prompts
* User can delete a prompt
* Only a user can access or modify their own prompts

## Tasks
- [x] Create a Prompt model
- [x] Create Prompt views.py
- [x] Create a Prompt serializer
- [x] Set up permissions and queryset
